name: Build

on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up build environment
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
      sudo apt-get install -y build-essential g++-aarch64-linux-gnu


      - name: Build project
        run: |
          aarch64-linux-gnu-g++ -std=c++11 -static -o Manjusaka Manjusaka.cpp


      - name: Store binary in summary
        uses: actions/upload-artifact@v2
        with:
          name: Manjusaka
          path: ./Manjusaka
