name: Manjusaka

on:
  push:
    branches:
      - 'Action'
  pull_request:
    branches:
      - 'Action'

env:
  GCC_CLONE_PATH: "${{ github.workspace }}/aarch64-linux-musl-gcc"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ssh git cmake
          sudo apt-get install -y default-jdk
      - name: Clone aarch64-linux-musl-gcc
        run: git clone https://github.com/chase535/aarch64-linux-musl-gcc.git ${GCC_CLONE_PATH} -b main --depth=1
      - name: Set C and C++ compiler
        run: |
          echo "CC=${GCC_CLONE_PATH}/bin/aarch64-linux-musl-gcc" >> ${GITHUB_ENV}
          echo "CXX=${GCC_CLONE_PATH}/bin/aarch64-linux-musl-g++" >> ${GITHUB_ENV}
      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake ..
          make
        
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Manjusaka
          path: ./build/Manjusaka
